pfsense/docs

source/virtualization/virtualizing-pfsense-with-proxmox.rst
Clean up from the mediaWiki syntax
=> Remove unnecessary Introduction heading

source/backup/configuration-backup-and-restore.rst
Corrected navigation and button language to match version 2.4.2_p1
=> Updated Navigation

source/dns/unbound-dns-resolver.rst
Add text to the docs that used to be part of the on-screen instructions prior to bootstrap changes.
Ref: https://github.com/pfsense/pfsense/pull/1606#issuecomment-410402802
=> Domain override with multiple DNS servers

source/cellular/known-working-3g-4g-modems.rst
Tested/verified w/ pfsense 2.4.4-RELEASE-p2 and APU2C4
Included additional info for interface and init string
=> Added Huawei E397u-53

source/vpn/ipsec/ipsec-compatibility.rst
Ubiquiti Unifi Security Gateway is working with Pfsense
=>  Ubiquiti Unifi Security Gateway is working with Pfsense

source/cellular/known-working-3g-4g-modems.rst
=> Update Known Working 3G-4G Modems

source/cellular/known-working-3g-4g-modems.rst
The modem/router worked the first time I plugged it into my Netgate.
=> Add ZTE MF985 to working cellular devices list

source/firewall/online-gaming-with-pfsense.rst
Added online gaming requirements for Nintendo Switch and Xbox One consoles.
=> Add Xbox One and Nintendo Switch NAT requirements

source/packages/installing-freebsd-packages.rst
Redmine Issue: https://redmine.pfsense.org/issues/10145
Ready for review
pfSense 2.4 / FreeBSD 11 update
=> Installing FreeBSD 11 Packages. Issue #10145

source/hardware/tuning-and-troubleshooting-network-cards.rst
Redmine Issue: https://redmine.pfsense.org/issues/10371
Ready for review
=> Chelsio cards tuning. Issue #10371

source/highavailability/configuring-high-availability.rst
Redmine Issue: https://redmine.pfsense.org/issues/9638
Ready for review
=> XMLRPC HA sync user. Issue #9638

source/dns/unbound-dns-resolver.rst
Redmine Issue: https://redmine.pfsense.org/issues/9461
Ready for review
=> Correction #9461

source/install/upgrade-troubleshooting.rst
https://redmine.pfsense.org/issues/10561
=> Correction #10561

source/cellular/known-working-3g-4g-modems.rst
https://redmine.pfsense.org/issues/10567
=> Correction #10567

source/cellular/known-working-3g-4g-modems.rst
https://redmine.pfsense.org/issues/10578
=> Huawei ME909u-521 4G/LTE Mini-PCIe init string. Correction #10578

source/highavailability/configuring-high-availability.rst
https://redmine.pfsense.org/issues/10262
=> Correction #10262

source/dhcp/dhcpv6-server.rst
https://redmine.pfsense.org/issues/9651
/56 (16 /56s)
=> Correction #9651

source/cellular/known-working-3g-4g-modems.rst
https://redmine.pfsense.org/issues/10598
=> Correction #10598

source/monitoring/monitoring-bandwidth-usage.rst
https://redmine.pfsense.org/issues/10604
=> Correction #10604

source/packages/fixing-a-broken-pkg-database.rst
https://redmine.pfsense.org/issues/10631
=> Correction #10631

source/vpn/android-vpn-compatibility.rst
I don't think this warrants its own troubleshooting page, so this page seemed like a good place to add the note.
=> Add note about using Android Private DNS alongside VPN
